name: GuessTuples
dependencies:
  - python=3.9
  - pytorch=1.8.1  cudatoolkit=11.1 # conda install pytorch cudatoolkit=11.1 -c pytorch -c conda-forge
  - matplotlib=3.4.1
  - python-dateutil=2.8.1
  - tensorboard-2.4.1